pipeline:
  name: check stage tplts
  identifier: check_stage_tplts
  projectIdentifier: harness_generic_template
  orgIdentifier: stf
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: stfgit/mower-java
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: check sources
        identifier: check_sources
        template:
          templateRef: account.source_code_scan
          versionLabel: v0.1
          gitBranch: main
          templateInputs:
            type: SecurityTests
            spec:
              infrastructure:
                type: KubernetesDirect
                spec:
                  connectorRef: <+input>
                  namespace: <+input>.default(harness-ci)
              execution:
                steps:
                  - parallel:
                      - step:
                          identifier: owasp
                          type: Owasp
                          spec:
                            resources:
                              limits:
                                memory: <+input>.default(2Gi)
                                cpu: <+input>.default(500m)
                      - step:
                          identifier: aquatrivy
                          type: AquaTrivy
                          spec:
                            resources:
                              limits:
                                memory: <+input>
                                cpu: <+input>
                      - step:
                          identifier: gitleaks
                          type: Gitleaks
                          spec:
                            resources:
                              limits:
                                memory: <+input>
                                cpu: <+input>
            delegateSelectors: <+input>
    - stage:
        name: build and push
        identifier: build_and_push
        template:
          templateRef: account.maven_build_stage_tplt
          versionLabel: v0.1
          gitBranch: main
          templateInputs:
            type: CI
            spec:
              infrastructure:
                type: KubernetesDirect
                spec:
                  connectorRef: <+input>
                  namespace: <+input>.default(harness-ci)
              execution:
                steps:
                  - step:
                      identifier: mvn_build
                      type: Run
                      spec:
                        connectorRef: <+input>
                        image: <+input>.default(maven:3.9.6-eclipse-temurin-21)
                        resources:
                          limits:
                            memory: <+input>
                            cpu: <+input>
                  - step:
                      identifier: mvn_test_with_coverage
                      type: Run
                      spec:
                        connectorRef: <+input>
                        image: <+input>.default(maven:3.9.6-eclipse-temurin-21)
                        resources:
                          limits:
                            memory: <+input>
                            cpu: <+input>
                  - step:
                      identifier: coverage_quality_gate
                      type: Run
                      spec:
                        connectorRef: <+input>
                        image: <+input>.default(alpine:latest)
                        resources:
                          limits:
                            memory: <+input>
                            cpu: <+input>
                  - step:
                      identifier: build_and_push_docker_image
                      type: BuildAndPushDockerRegistry
                      spec:
                        connectorRef: <+input>
                        repo: <+input>
                        resources:
                          limits:
                            memory: <+input>
                            cpu: <+input>
            delegateSelectors: <+input>
    - stage:
        name: check images
        identifier: check_images
        template:
          templateRef: account.images_scan
          versionLabel: v0.1
          gitBranch: main
          templateInputs:
            type: SecurityTests
            spec:
              infrastructure:
                type: KubernetesDirect
                spec:
                  connectorRef: <+input>
                  namespace: <+input>.default(harness-ci)
              execution:
                steps:
                  - step:
                      identifier: aquatrivy_container
                      type: AquaTrivy
                      spec:
                        resources:
                          limits:
                            memory: <+input>
                            cpu: <+input>
            delegateSelectors: <+input>
    - stage:
        name: rollout deploy
        identifier: rollout_deploy_dev
        tags: {}
        template:
          templateRef: account.deploy_k8s
          versionLabel: v0.1
          gitBranch: main
          templateInputs:
            type: Deployment
            spec:
              environment:
                environmentRef: <+input>
                environmentInputs: <+input>
                serviceOverrideInputs: <+input>
                infrastructureDefinitions: <+input>
              service:
                serviceRef: <+input>
                serviceInputs: <+input>
            delegateSelectors: <+input>
    - stage:
        name: jira approval
        identifier: jira_approval
        tags: {}
        template:
          templateRef: account.jira_approval
          versionLabel: v0.1
          gitBranch: main
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: create_ticket
                      type: JiraCreate
                      spec:
                        connectorRef: account.jira_stf_connector
                        projectKey: NN
                        issueType: Déploiement
  delegateSelectors:
    - delegate-k8s-docacloud
