pipeline:
  name: harness generic
  identifier: harness_generic
  projectIdentifier: <+input>
  orgIdentifier: <+input>
  variables:
    - name: environment
      type: String
      value: <+input>.allowedValues(dev, staging, prod)
    - name: buildTool
      type: String
      value: <+input>.allowedValues(npm, maven, yarn)
    - name: dockerImage
      type: String
      value: <+input>.default(node:20-alpine)
    - name: dockerRegistry
      type: String
      value: <+input>
    - name: k8sCluster
      type: String
      value: <+input>
    - name: deployNamespace
      type: String
      value: <+input>.default(default)
    - name: secretApiKey
      type: Secret
      value: <+input>
  stages:
    - stage:
        name: Build Stage
        identifier: build_stage
        template:
          templateRef: build_stage_template
          versionLabel: v0.1
          templateInputs:
            type: CI
            spec:
              infrastructure:
                spec:
                  connectorRef: <+pipeline.variables.dockerRegistry>
              execution:
                steps:
                  - step:
                      identifier: run_build
                      type: Run
                      spec:
                        image: <+pipeline.variables.dockerImage>
                        command: |
                          if [ "<+pipeline.variables.buildTool>" = "npm" ]; then
                            npm ci && npm run build
                          elif [ "<+pipeline.variables.buildTool>" = "maven" ]; then
                            mvn clean install
                          fi
    - stage:
        name: Audit Stage
        identifier: audit_stage
        template:
          templateRef: audit_stage_template
          versionLabel: v0.1
    - stage:
        name: Deploy Stage
        identifier: deploy_stage
        template:
          templateRef: deploy_stage_template
          versionLabel: v0.1
          templateInputs:
            type: Deployment
            spec:
              environment:
                environmentRef: <+pipeline.variables.environment>
              infrastructureDefinitions:
                - identifier: <+pipeline.variables.k8sCluster>
              execution:
                steps:
                  - step:
                      identifier: deploy_echo
                      type: ShellScript
                      spec:
                        shell: Bash
                        script: |
                          echo "🟢 Déploiement de <+pipeline.variables.buildTool> vers <+pipeline.variables.environment> sur le namespace <+pipeline.variables.deployNamespace>"
                          echo "🔐 Clé API : <+secrets.getValue('pipeline.variables.secretApiKey')>"
