pipeline:
  name: Security Demo - Enterprise Hardened
  identifier: security_demo_pipeline
  projectIdentifier: harness_generic_template
  orgIdentifier: stf
  tags:
    security: demo
    environment: hardened
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: <+input>
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: Pre-Security Validation
        identifier: pre_security_validation
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Run
                  name: Pipeline Security Initialization
                  identifier: pipeline_security_init
                  spec:
                    connectorRef: org.Dockerhub
                    image: alpine:3.19-slim
                    shell: Sh
                    command: |
                      echo "🚀 ENTERPRISE SECURITY PIPELINE INITIALIZED"
                      echo "============================================"
                      echo "📅 Pipeline Start: $(date -Iseconds)"
                      echo "🔒 Security Level: ENTERPRISE HARDENED"
                      echo "📋 Compliance: SOX, GDPR, CIS, NIST"
                      echo "🔍 Repository: <+codebase.repoName>"
                      echo "🌿 Branch: <+codebase.branch>"
                      echo "✅ Pre-security validation completed"
    - stage:
        name: Source Code Security Scan - Hardened
        identifier: source_security_scan_hardened
        template:
          templateRef: account.source_code_scan
          versionLabel: v0.3
          templateInputs:
            type: SecurityTests
            spec:
              infrastructure:
                type: KubernetesDirect
                spec:
                  connectorRef: <+input>.default(account.k8sdocacloud)
                  namespace: <+input>.default(harness-ci)
              execution:
                steps:
                  - parallel:
                      - step:
                          identifier: owasp
                          type: Owasp
                          spec:
                            advanced:
                              fail_on_severity: <+input>.default(medium)
                            resources:
                              limits:
                                memory: <+input>.default(4Gi)
                                cpu: <+input>.default(2000m)
                      - step:
                          identifier: aquatrivy
                          type: AquaTrivy
                          spec:
                            advanced:
                              fail_on_severity: <+input>.default(medium)
                            resources:
                              limits:
                                memory: <+input>.default(3Gi)
                                cpu: <+input>.default(1500m)
                      - step:
                          identifier: gitleaks
                          type: Gitleaks
                          spec:
                            advanced:
                              fail_on_severity: <+input>.default(low)
                            resources:
                              limits:
                                memory: <+input>.default(2Gi)
                                cpu: <+input>.default(1000m)
                  - step:
                      identifier: security_summary
                      type: Run
                      spec:
                        connectorRef: <+input>
            delegateSelectors: <+input>
    - stage:
        name: Secure Build and Package
        identifier: secure_build_package
        template:
          templateRef: account.npm_build
          versionLabel: v0.1
          templateInputs:
            type: CI
            spec:
              infrastructure:
                type: KubernetesDirect
                spec:
                  connectorRef: <+input>.default(account.k8sdocacloud)
                  namespace: <+input>.default(harness-ci)
              execution:
                steps:
                  - step:
                      identifier: Install_Dependencies
                      type: Run
                      spec:
                        connectorRef: <+input>.default(org.Dockerhub)
                        image: <+input>.default(node:20)
                  - step:
                      identifier: ESLint_Check
                      type: Run
                      spec:
                        connectorRef: <+input>
                        image: <+input>.default(node:20)
                  - step:
                      identifier: Build_Application
                      type: Run
                      spec:
                        connectorRef: <+input>
                        image: <+input>.default(node:20)
                  - step:
                      identifier: Unit_Tests
                      type: Run
                      spec:
                        connectorRef: <+input>
                        image: <+input>.default(node:20)
                  - step:
                      identifier: NPM_Audit
                      type: Run
                      spec:
                        connectorRef: <+input>
                        image: <+input>.default(node:20)
                  - step:
                      identifier: BuildAndPushDockerRegistry_1
                      type: BuildAndPushDockerRegistry
                      spec:
                        connectorRef: <+input>.default(org.Dockerhub)
                        repo: <+input>
    - stage:
        name: Container Security Scan - Hardened
        identifier: container_security_scan_hardened
        template:
          templateRef: account.images_scan
          versionLabel: v0.3
          templateInputs:
            type: SecurityTests
            spec:
              infrastructure:
                type: KubernetesDirect
                spec:
                  connectorRef: <+input>.default(account.k8sdocacloud)
                  namespace: <+input>.default(harness-ci)
              execution:
                steps:
                  - step:
                      identifier: pre_image_validation
                      type: Run
                      spec:
                        connectorRef: <+input>
                  - step:
                      identifier: aquatrivy_container
                      type: AquaTrivy
                      spec:
                        advanced:
                          fail_on_severity: <+input>.default(medium)
                        resources:
                          limits:
                            memory: <+input>.default(4Gi)
                            cpu: <+input>.default(2000m)
                        image:
                          type: docker_v2
                          tag: <+input>.default(latest)
                          name: <+input>
                  - step:
                      identifier: additional_security_validation
                      type: Run
                      spec:
                        connectorRef: <+input>
                  - step:
                      identifier: container_security_report
                      type: Run
                      spec:
                        connectorRef: <+input>
            delegateSelectors: <+input>
    - stage:
        name: Security Policy Enforcement
        identifier: security_policy_enforcement
        template:
          templateRef: account.security_policies
          versionLabel: v0.1
          templateInputs:
            type: Custom
            spec:
              infrastructure:
                type: KubernetesDirect
                spec:
                  connectorRef: <+input>.default(account.k8sdocacloud)
                  namespace: <+input>.default(harness-governance)
              execution:
                steps:
                  - step:
                      identifier: security_policy_validation
                      type: Run
                      spec:
                        connectorRef: <+input>
                  - step:
                      identifier: artifact_security_validation
                      type: Run
                      spec:
                        connectorRef: <+input>
                  - step:
                      identifier: policy_decision_point
                      type: Run
                      spec:
                        connectorRef: <+input>
                  - step:
                      identifier: final_compliance_report
                      type: Run
                      spec:
                        connectorRef: <+input>
            delegateSelectors: <+input>
    - stage:
        name: Security Team Approval
        identifier: security_team_approval
        template:
          templateRef: account.manual_approval
          versionLabel: v0.1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: approval
                      type: HarnessApproval
                      spec:
                        approvers:
                          minimumCount: <+input>.default(1)
                          userGroups: <+input>.default(org.DevOps_Team)
            delegateSelectors: <+input>
        when:
          pipelineStatus: Success
          condition: <+input>.default("true")
    - stage:
        name: Secure Deploy to Dev
        identifier: secure_deploy_dev
        template:
          templateRef: account.deploy_k8s
          versionLabel: v0.1
          templateInputs:
            type: Deployment
            spec:
              environment:
                environmentRef: <+input>.default(dev)
                environmentInputs: <+input>
                serviceOverrideInputs: <+input>
                infrastructureDefinitions: <+input>
              service:
                serviceRef: <+input>
                serviceInputs: <+input>
            delegateSelectors: <+input>
  variables:
    - name: security_level
      type: String
      value: ENTERPRISE_HARDENED
      description: Level of security enforcement
    - name: compliance_frameworks
      type: String
      value: SOX,GDPR,CIS,NIST
      description: Required compliance frameworks
    - name: manual_approval_required
      type: String
      value: "true"
      description: Require manual security approval
  delegateSelectors: <+input>
  notificationRules:
    - name: security_notifications
      identifier: security_notifications
      pipelineEvents:
        - type: PipelineFailed
        - type: StageFailed
          forStages:
            - source_security_scan_hardened
            - container_security_scan_hardened
            - security_policy_enforcement
      notificationMethod:
        type: Email
        spec:
          userGroups:
            - org._organization_all_users
          recipients: []
      enabled: true
